language: python
sudo: false
cache:
  directories:
    - ~/.cache/pip
env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
addons:
  apt:
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev
matrix:
  include:
    # For each python version, we test
    # rasterio 0.36, the most recent release and master
    - python: 2.7
      env: RASTERIO=0.36
    - python: 2.7
      env: RASTERIO=recent
    - python: 2.7
      env: RASTERIO=master
    - python: 3.6
      env: RASTERIO=0.36
    - python: 3.6
      env: RASTERIO=recent
    - python: 3.6
      env: RASTERIO=master

before_install:
  - pip install -U pip
  - pip install wheel
install:
  - if [[ $RASTERIO == 'master' ]]; then pip install numpy cython; pip install git+https://github.com/mapbox/rasterio.git#egg=rasterio; elif [[ $RASTERIO == 'recent' ]]; then pip wheel rasterio; pip install rasterio; else pip wheel "rasterio==$RASTERIO"; pip install "rasterio==$RASTERIO"; fi
  - pip install -r requirements-dev.txt
  - pip install -e .
  - pip install coveralls
script: "py.test --cov merge_rgba --cov-report term-missing"
after_success:
  - coveralls
