language: python
sudo: false
cache:
  directories:
    - ~/.cache/pip
env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
matrix:
  include:
    - python: 3.6
before_install:
  - pip install -U pip
  - pip install wheel
install:
  - pip install -r requirements-dev.txt
  - pip install -e .
  - pip install coveralls
script: "py.test --cov merge_rgba --cov-report term-missing"
after_success:
  - coveralls
